name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install && sudo apt install genisoimage

      - name: Load game.config.json
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'game.config.json'
          prefix: game

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/web

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "${{ env.game_title }} latest build"
          files: |
            ./dist/game-web.zip
            ./dist/game-win.zip
            ./dist/game-mac.dmg
            ./dist/game-linux.zip

      - name: Upload to Itch
        if: ${{env.game_itch_upload  == 'true'}}
        uses: Ayowel/butler-to-itch@v1.0.0
        with:
          butler_key: ${{ secrets.BUTLER_CREDENTIALS }}
          itch_user: ${{ env.game_itch_username }}
          itch_game: ${{ env.game_itch_game }}
          files: |
            ./dist/game-web.zip
            ./dist/game-win.zip
            ./dist/game-mac.dmg
            ./dist/game-linux.zip
          auto_channel: true
          butler_version: "latest"
          check_signature: false
